// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Course struct {
	IDCourses   string  `json:"id_courses"`
	Nombre      *string `json:"nombre"`
	Descripcion *string `json:"descripcion"`
	Temas       *string `json:"temas"`
}

type Record struct {
	IDRecords  string   `json:"id_records"`
	Student    *Student `json:"student"`
	Course     *Course  `json:"course"`
	Startdate  *string  `json:"startdate"`
	Finishdate *string  `json:"finishdate"`
}

type Student struct {
	Dni             string  `json:"dni"`
	Nombre          *string `json:"nombre"`
	Direccion       *string `json:"direccion"`
	FechaNacimiento *string `json:"fecha_nacimiento"`
}
